### ISSUE TITLE
Better naming of release builds

### ISSUE THREAD

**Issue by dkastl** [Georepublic/lobsta_client#1]
Right now the artefacts built and attached to releases are always named the same, default name.

It would be better to have them named by their release name and version, and this should be possible using the GH Action tool:
https://github.com/ncipollo/release-action#example

As far as I understand it takes the `tag` name of a release, but for that the action should be triggered through creating a tag rather than manually creating a release.

There could be an issue with creating a tag that shouldn't be a release, but I would say this "risk" is low.

**Comment by mbasa-georepublic** [comment]
See TestBuild_v0.0.5.
