### ISSUE TITLE
Add photo from different sources

### ISSUE THREAD

**Issue by dkastl** [Georepublic/lobsta_client#15]
Currently "Add photo" opens a file browser. So if the photo isn't there but needs to be take first, then user needs to open the camera app, take a photo, go back to the LOBSTA client, search the photo in the file system.

More user friendly would be multiple ways to add a photo:
- select a photo from the file system
- take a photo

**Comment by mbasa-georepublic** [comment]
Camera option for photo upload functionality has been added.
