### ISSUE TITLE
Start and Due Date set to "today" by default

### ISSUE THREAD

**Issue by dkastl** [Georepublic/lobsta_client#16]
In Redmine the Start and Due Date are not required and empty by default.

Right now the dates are set and there is no way to unset the dates at the time of creation nor later. \
Additional to that some user may not have the permission to see or edit this information.

**Comment by mbasa-georepublic** [comment]
Dates are assigned by default on easyRedmine.

**Comment by dkastl** [comment]
Is this a good idea?

And I tried it and indeed it sets the "Start Date" to "today" but the "Due Date" is "undefined" and not set. Also once set the date cannot be unset.

For me this is not a user-friendly feature. Is it difficult to unset the date and not select one by default?

**Comment by mbasa-georepublic** [comment]
will leave it blank on issue input.

**Comment by mbasa-georepublic** [comment]
<img width="797" alt="Screen Shot 2022-01-25 at 16 48 11" src="https://user-images.githubusercontent.com/68265868/150933845-da6d7c5c-b69d-45ad-bb83-64ac9ac1c5da.png">

**Comment by mbasa-georepublic** [comment]
can there be a due date without a start date?

**Comment by dkastl** [comment]
In Redmine this is possible. There are no restrictions on that.

![Screenshot from 2022-01-25 16-53-23](https://user-images.githubusercontent.com/227762/150934665-f430fc4f-03db-4b45-a271-a4687ef75122.png)

I'm wondering how "Field Permissions" would be delivered through the API 
https://redmine.org/projects/redmine/wiki/RedmineIssueTrackingSetup#Fields-permissions

**Comment by mbasa-georepublic** [comment]
the start_date and due_date defaults to a blank when creating a new Issue.
