### ISSUE TITLE
Support other attachments

### ISSUE THREAD

**Issue by dkastl** [Georepublic/lobsta_client#19]
At the moment only photos can be added to issues. 

For LOBSTA users other file types may be useful as well to be attached.

**Comment by mbasa-georepublic** [comment]
**Added a PDF viewer to view PDF attachments.**



![Simulator Screen Shot - iPhone 13 - 2022-01-30 at 13 45 25](https://user-images.githubusercontent.com/68265868/151727368-2e1b9566-6c02-4512-a62b-f28972be3aac.png)

**Comment by mbasa-georepublic** [comment]
**PDF Viewer Screen**

![Simulator Screen Shot - iPhone 13 - 2022-01-30 at 13 46 04](https://user-images.githubusercontent.com/68265868/151727451-50811100-a106-425c-957f-2d96eada5732.png)

**Comment by dkastl** [comment]
Thanks!
Could you reference this with a pull request?
As far as I understand, this would make the feature automatically appear in the release notes then.
