### ISSUE TITLE
Support multiple accounts

### ISSUE THREAD

**Issue by dkastl** [Georepublic/lobsta_client#25]
## Current situation

A user needs to logout when switching the account

## New functionality

A user can login to multiple accounts and switch between accounts. \
An account is defined through `login ID` and `instance URL`.

## Note

It's OK to complete the implementation of the UI at a later time, but it's probably a good idea to consider this feature already in the application model.

**Comment by mbasa-georepublic** [comment]
Switch Account functionality has been added.
